image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  AWS_REGION: $AWS_DEFAULT_REGION
  KUBECONFIG: "/kube/config"

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache python3 py3-pip
  - pip3 install awscli
  # Configure AWS and login to ECR
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_DEFAULT_REGION
  - eval $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY)

build:
  stage: build
  script:
    - docker build -t $ECR_REPOSITORY:$CI_COMMIT_SHA .
    - docker push $ECR_REPOSITORY:$CI_COMMIT_SHA
  only:
    - main

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    # Write kubeconfig file
    - mkdir -p /kube
    - echo "$KUBE_CONFIG" > /kube/config
    
    # Replace IMAGE_PLACEHOLDER with the actual image URI
    - sed -i "s|IMAGE_PLACEHOLDER|$ECR_REPOSITORY:$CI_COMMIT_SHA|g" cicd/react-app-deployment.yaml
    
    # Apply the Kubernetes manifests
    - kubectl apply -f cicd/react-app-deployment.yaml
    - kubectl apply -f cicd/react-app-service.yaml
  only:
    - main

